name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    uses: ./.github/workflows/build.yml
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
