name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
